apiVersion: v1
kind: ConfigMap
metadata:
  name: primes-config
  namespace: primes
data:
  REDIS_HOST: "redis.primes.svc.cluster.local"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  APP_ENV: "kubernetes"
