apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: primes
type: Opaque
stringData:
  password: "primes_pass"
  username: "primes_user"
  database: "primes"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: primes
type: Opaque
stringData:
  database-url: "postgresql://primes_user:primes_pass@postgres.primes.svc.cluster.local:5432/primes"
